server:
  port: 8088
spring:
  application:
    name: spring
  datasource:
    password: 123456
    url: jdbc:mysql://localhost:3306/springdb?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver